//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class brand
    {
        public Nullable<int> brandid { get; set; }
        public string brandName { get; set; }
        public string image { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
