//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courier_Detail
    {
        public int Id { get; set; }
        public string FromWeight { get; set; }
        public string ToWeight { get; set; }
        public string Unit { get; set; }
        public string RajCourier_Fees { get; set; }
        public string RajCourier_Name { get; set; }
        public string NICourier_Fees { get; set; }
        public string NICourier_Name { get; set; }
        public string ROICourier_Fees { get; set; }
        public string ROICourier_Name { get; set; }
        public string NECourier_Fees { get; set; }
        public string NECourier_Name { get; set; }
    }
}
