//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class friendsmobileEntities : DbContext
    {
        public friendsmobileEntities()
            : base("name=friendsmobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminLogin> AdminLogins { get; set; }
        public DbSet<blog_detail> blog_detail { get; set; }
        public DbSet<brand> brands { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Courier_Detail> Courier_Detail { get; set; }
        public DbSet<dtl_ProductGallery> dtl_ProductGallery { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<Loc_District> Loc_District { get; set; }
        public DbSet<Loc_State> Loc_State { get; set; }
        public DbSet<M_CategoryMaster> M_CategoryMaster { get; set; }
        public DbSet<ProductSizeQuantity> ProductSizeQuantities { get; set; }
        public DbSet<register> registers { get; set; }
        public DbSet<temp_ProColorSize> temp_ProColorSize { get; set; }
        public DbSet<temp_progallery> temp_progallery { get; set; }
        public DbSet<TrnCart> TrnCarts { get; set; }
        public DbSet<TrnOrderDetail> TrnOrderDetails { get; set; }
        public DbSet<TrnOrderMain> TrnOrderMains { get; set; }
        public DbSet<TrnWallet> TrnWallets { get; set; }
        public DbSet<wishlist> wishlists { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<varient> varients { get; set; }
    }
}
