//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc_State
    {
        public short State_Code { get; set; }
        public string State_Name { get; set; }
        public short Country_Code { get; set; }
        public byte State_Priority { get; set; }
        public bool State_Active { get; set; }
        public string CourierState { get; set; }
    }
}
