//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSizeQuantity
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Size { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime RTS { get; set; }
        public int ColorId { get; set; }
        public Nullable<int> urate { get; set; }
        public Nullable<int> udiscount { get; set; }
        public Nullable<int> arate { get; set; }
        public Nullable<int> adiscount { get; set; }
    }
}
