//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int categoryid { get; set; }
        public int productid { get; set; }
        public string productname { get; set; }
        public Nullable<int> qty { get; set; }
        public string image { get; set; }
        public Nullable<int> Brandid { get; set; }
        public string Description { get; set; }
        public Nullable<bool> sale { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> visit { get; set; }
        public Nullable<System.DateTime> rts { get; set; }
        public string metatitle { get; set; }
    }
}
