//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnCart
    {
        public int AID { get; set; }
        public int Id { get; set; }
        public Nullable<int> CartId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public bool ActiveStatus { get; set; }
        public System.DateTime RTS { get; set; }

        public string pid { get; set; }
        public string pqty { get; set; }
    }
}
