//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnOrderMain
    {
        public int AID { get; set; }
        public int OrderId { get; set; }
        public int Usercode { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal WalletAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal TotalQuantity { get; set; }
        public bool IsWalletDeduct { get; set; }

        public decimal DeliveryFees { get; set; }
        public decimal Amount { get; set; }
        public string Paymode { get; set; }
        public string TrnId { get; set; }
        public string TrnStatus { get; set; }
        public string OrderThrough { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingMobileNo { get; set; }
        public string ShippingEmailId { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingZipcode { get; set; }
        public string ShippingStats { get; set; }
        public bool Delivered { get; set; }
        public bool Cancelled { get; set; }
        public bool Returned { get; set; }
        public bool Dispatched { get; set; }
        public bool Settlement { get; set; }
        public System.DateTime RTS { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PromoCodeId { get; set; }
        public int PromoCodeAmount { get; set; }
        public int DeliveryboyId { get; set; }
        public string FranchiseMessage { get; set; }
        public string remark { get; set; }
        public Nullable<int> sid { get; set; }
    }
}
