//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_FranchiseMaster
    {
        public int AID { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int DistCode { get; set; }
        public int StateCode { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string AdharCardNo { get; set; }
        public string Occupation { get; set; }
        public int AdminCode { get; set; }
        public bool ActiveStatus { get; set; }
        public System.DateTime RTS { get; set; }
        public short District_Code { get; set; }
        public string District_Name { get; set; }
        public short State_Code { get; set; }
        public string State_Name { get; set; }
        public string Admin_Name { get; set; }
        public int Admin_Code { get; set; }
        public string Admin_Password { get; set; }
    }
}
