//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductDetailStore
    {
        public string storename { get; set; }
        public Nullable<int> DeliveryFees { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Image { get; set; }
        public Nullable<int> Weight { get; set; }
        public int Discount { get; set; }
        public bool Active { get; set; }
        public string Type { get; set; }
        public string SchemeOffer { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string MainCategoryName { get; set; }
        public bool IsMixed { get; set; }
        public Nullable<int> TotalPicture { get; set; }
    }
}
