//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductDetailShow
    {
        public int Storeid { get; set; }
        public string StoreName { get; set; }
        public string District { get; set; }
        public Nullable<int> DeliveryFees { get; set; }
        public int ProductId { get; set; }
        public string Type { get; set; }
        public Nullable<int> Rate { get; set; }
        public int Discount { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductName { get; set; }
        public string Image { get; set; }
        public string Unit { get; set; }
        public string MainCategoryName { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<int> Weight { get; set; }
        public string SchemeOffer { get; set; }
        public string ProductCode { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public string ColorName { get; set; }
        public int Subcategoryid { get; set; }
        public int MaincategoryId { get; set; }
        public Nullable<bool> SaleProductActive { get; set; }
        public Nullable<bool> Citystoreoffers { get; set; }
        public Nullable<int> NationalPrice { get; set; }
        public Nullable<int> NationalDiscount { get; set; }
        public Nullable<bool> Iscombo { get; set; }
        public string Description { get; set; }
    }
}
