//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityStoreAPIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StoreOrder
    {
        public string ProductName { get; set; }
        public string Image { get; set; }
        public Nullable<int> NetAmount { get; set; }
        public Nullable<int> QuantityActual { get; set; }
        public string UnitActual { get; set; }
        public Nullable<int> WeightActual { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string Delivered { get; set; }
        public Nullable<int> UserCode { get; set; }
    }
}
